var car = "subaru";
console.log("is car == 'subaro'? predicat true");
console.log(car == 'subaru');
console.log("is car != 'honda city'? predicate true");
console.log(car != 'honda city');
console.log("is car == 'subaru'? predicate false");
console.log(car == 'subaru');
console.log("is car =='SUBARU'? predicate false");
console.log(car == 'SUBARU');
console.log("is car.lenght == 6? predicat");
console.log(car.length == 6);
console.log("is car.lenght != 10? predicate true");
console.log(car.length != 10);
console.log("is 10 > 45 ? predicate false");
console.log(10 > 45);
console.log("is 3 <= 2 ? predicate false");
console.log(3 <= 2);
console.log("is 72 >= 83 ? predict false");
console.log(73 >= 83);
console.log("is car == 'subaru' && car.lenght == 6? predict true");
console.log(car == 'subaru' && car.length == 6);
